// Package bundle packages scan findings into a complete bug bounty
// submission: Markdown report with PoC code, curl commands, severity
// breakdown, and remediation advice — ready to submit to any platform.
package bundle

import (
	"archive/zip"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// ── Types ────────────────────────────────────────────────────────────────

// Pack contains all parts of a bug bounty submission bundle.
type Pack struct {
	Target    string
	Date      time.Time
	Findings  []Finding
	Stats     Stats
	Remedies  map[string]string
}

// Finding is a single vulnerability entry.
type Finding struct {
	Type      string `json:"type"`
	URL       string `json:"url"`
	Severity  string `json:"severity"`
	Parameter string `json:"parameter"`
	Payload   string `json:"payload"`
	Evidence  string `json:"evidence"`
	PoC       string `json:"poc,omitempty"`
}

// Stats holds summary counts.
type Stats struct {
	Total    int
	Critical int
	High     int
	Medium   int
	Low      int
	Info     int
}

// ── Builder ───────────────────────────────────────────────────────────────

// New creates a Pack from findings and target info.
func New(target string, findings []Finding) *Pack {
	p := &Pack{
		Target:   target,
		Date:     time.Now(),
		Findings: findings,
	}
	// Sort by severity
	sort.Slice(p.Findings, func(i, j int) bool {
		return sevNum(p.Findings[i].Severity) > sevNum(p.Findings[j].Severity)
	})
	// Count
	for _, f := range findings {
		p.Stats.Total++
		switch strings.ToUpper(f.Severity) {
		case "CRITICAL": p.Stats.Critical++
		case "HIGH": p.Stats.High++
		case "MEDIUM": p.Stats.Medium++
		case "LOW": p.Stats.Low++
		default: p.Stats.Info++
		}
	}
	return p
}

// ── Output formats ───────────────────────────────────────────────────────

// Markdown generates a full bug bounty report in Markdown.
func (p *Pack) Markdown() string {
	var sb strings.Builder
	sb.WriteString("# Bug Bounty Report — sxsc\n\n")
	sb.WriteString(fmt.Sprintf("**Target:** `%s`  \n", p.Target))
	sb.WriteString(fmt.Sprintf("**Date:** %s  \n", p.Date.Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("**Total Findings:** %d  \n\n", p.Stats.Total))

	sb.WriteString("## Summary\n\n")
	sb.WriteString("| Severity | Count |\n|---|---|\n")
	sb.WriteString(fmt.Sprintf("| CRITICAL | %d |\n", p.Stats.Critical))
	sb.WriteString(fmt.Sprintf("| HIGH | %d |\n", p.Stats.High))
	sb.WriteString(fmt.Sprintf("| MEDIUM | %d |\n", p.Stats.Medium))
	sb.WriteString(fmt.Sprintf("| LOW | %d |\n", p.Stats.Low))
	sb.WriteString(fmt.Sprintf("| INFO | %d |\n\n", p.Stats.Info))

	sb.WriteString("## Findings\n\n")
	for i, f := range p.Findings {
		sb.WriteString(fmt.Sprintf("### [%d] %s — `%s`\n\n", i+1, f.Type, f.Severity))
		sb.WriteString(fmt.Sprintf("- **URL:** `%s`\n", f.URL))
		sb.WriteString(fmt.Sprintf("- **Parameter:** `%s`\n", f.Parameter))
		sb.WriteString(fmt.Sprintf("- **Payload:** `%s`\n", f.Payload))
		sb.WriteString(fmt.Sprintf("- **Evidence:** %s\n", f.Evidence))
		if f.PoC != "" {
			sb.WriteString(fmt.Sprintf("\n**Proof of Concept:**\n\n```\n%s\n```\n", f.PoC))
		}
		if rem, ok := p.Remedy(f.Type); ok {
			sb.WriteString(fmt.Sprintf("\n**Remediation:** %s\n", rem))
		}
		sb.WriteString("\n---\n\n")
	}

	sb.WriteString("\n*Report generated by sxsc — SentinelX Scanner*\n")
	return sb.String()
}

// ── ZIP export ───────────────────────────────────────────────────────────

// Zip creates a ZIP archive containing the Markdown report and any
// supporting evidence files. Ready to attach to a bug bounty submission.
func (p *Pack) Zip(dir string) (string, error) {
	md := p.Markdown()
	zipPath := filepath.Join(dir, fmt.Sprintf("sxsc-bounty-%s.zip", p.Date.Format("2006-01-02-150405")))

	f, err := os.Create(zipPath)
	if err != nil {
		return "", err
	}
	defer f.Close()

	w := zip.NewWriter(f)
	defer w.Close()

	// Markdown report
	reportFile, _ := w.Create("report.md")
	io.WriteString(reportFile, md)

	// findings.json — machine-readable findings
	jsonFile, _ := w.Create("findings.json")
	io.WriteString(jsonFile, toJSON(p))

	// Per-finding PoC files
	for i, f := range p.Findings {
		if f.PoC != "" {
			pocName := fmt.Sprintf("poc-%d-%s.txt", i+1, safeFilename(f.Type))
			pocFile, _ := w.Create(pocName)
			io.WriteString(pocFile, f.PoC)
		}
	}

	return zipPath, nil
}

// ── Helpers ──────────────────────────────────────────────────────────────

// Remedy returns remediation advice for a finding type.
func (p *Pack) Remedy(findingType string) (string, bool) {
	up := strings.ToUpper(findingType)
	remedies := map[string]string{
		"SQL INJECTION":             "Use parameterized queries or prepared statements. Never concatenate user input into SQL strings.",
		"XSS":                       "HTML-encode all user output. Implement Content-Security-Policy. Use auto-escaping template engines.",
		"COMMAND INJECTION":         "Never pass user input to shell commands. Use exec.Command with explicit argument lists (no shell=true).",
		"SSRF":                      "Whitelist outbound URLs. Block private IP ranges (169.254.x, 10.x, 127.x). Use IMDSv2 on AWS.",
		"XXE":                       "Disable external entity processing in XML parsers. Use JSON instead of XML where possible.",
		"LFI":                       "Whitelist allowed file paths. Use realpath() to canonicalize. Never use user input in include/require.",
		"PATH TRAVERSAL":            "Validate file paths against an allowlist. Canonicalize with realpath before access.",
		"IDOR":                      "Enforce ownership checks on every object access. Use unpredictable UUIDs instead of sequential IDs.",
		"JWT":                       "Always verify signatures server-side. Reject alg=none. Use strong (256-bit+) secrets for HMAC algorithms.",
		"OPEN REDIRECT":             "Validate redirect URLs against an allowlist. Never accept full URLs in redirect parameters.",
		"FILE UPLOAD":               "Validate file type by magic bytes. Store uploads outside web root. Strip executable permissions.",
		"CORS":                      "Specify exact origins. Never reflect arbitrary Origin headers. Avoid Access-Control-Allow-Credentials: true.",
		"CSRF":                      "Implement anti-CSRF tokens in all state-changing forms. Set SameSite=Lax or Strict on session cookies.",
		"PROTOTYPE POLLUTION":       "Use Object.create(null) for objects holding user keys. Validate and sanitize __proto__ and constructor properties.",
		"SUBDOMAIN TAKEOVER":        "Remove DNS records for decommissioned services. Verify CNAME targets are still registered and active.",
		"REQUEST SMUGGLING":         "Use HTTP/2 end-to-end. Disable backend connection reuse. Normalize ambiguous requests at the proxy.",
		"CACHE POISONING":           "Include all relevant headers in cache keys. Use Vary header. Disable caching of user-specific responses.",
		"INSECURE DESERIALIZATION":  "Never deserialize untrusted data. Use safe formats like JSON. Implement type allowlists and integrity checks.",
	}
	for key, rem := range remedies {
		if strings.Contains(up, key) {
			return rem, true
		}
	}
	return "Review OWASP guidelines for this vulnerability class.", false
}

func sevNum(s string) int {
	switch strings.ToUpper(s) {
	case "CRITICAL": return 5
	case "HIGH": return 4
	case "MEDIUM": return 3
	case "LOW": return 2
	default: return 1
	}
}

func safeFilename(s string) string {
	s = strings.ReplaceAll(s, " ", "-")
	s = strings.ReplaceAll(s, "/", "-")
	s = strings.ReplaceAll(s, "\\", "-")
	return strings.ToLower(s)
}

func toJSON(p *Pack) string {
	b, err := json.Marshal(struct {
		Target   string `json:"target"`
		Date     string `json:"date"`
		Total    int    `json:"total"`
		Critical int    `json:"critical"`
		High     int    `json:"high"`
		Medium   int    `json:"medium"`
	}{
		Target:   p.Target,
		Date:     p.Date.Format(time.RFC3339),
		Total:    p.Stats.Total,
		Critical: p.Stats.Critical,
		High:     p.Stats.High,
		Medium:   p.Stats.Medium,
	})
	if err != nil {
		return "{}"
	}
	return string(b)
}
